// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EDemoCommands int32

const (
	EDemoCommands_DEM_Error               EDemoCommands = -1
	EDemoCommands_DEM_Stop                EDemoCommands = 0
	EDemoCommands_DEM_FileHeader          EDemoCommands = 1
	EDemoCommands_DEM_FileInfo            EDemoCommands = 2
	EDemoCommands_DEM_SyncTick            EDemoCommands = 3
	EDemoCommands_DEM_SendTables          EDemoCommands = 4
	EDemoCommands_DEM_ClassInfo           EDemoCommands = 5
	EDemoCommands_DEM_StringTables        EDemoCommands = 6
	EDemoCommands_DEM_Packet              EDemoCommands = 7
	EDemoCommands_DEM_SignonPacket        EDemoCommands = 8
	EDemoCommands_DEM_ConsoleCmd          EDemoCommands = 9
	EDemoCommands_DEM_CustomData          EDemoCommands = 10
	EDemoCommands_DEM_CustomDataCallbacks EDemoCommands = 11
	EDemoCommands_DEM_UserCmd             EDemoCommands = 12
	EDemoCommands_DEM_FullPacket          EDemoCommands = 13
	EDemoCommands_DEM_SaveGame            EDemoCommands = 14
	EDemoCommands_DEM_SpawnGroups         EDemoCommands = 15
	EDemoCommands_DEM_Max                 EDemoCommands = 16
	EDemoCommands_DEM_IsCompressed        EDemoCommands = 64
)

var EDemoCommands_name = map[int32]string{
	-1: "DEM_Error",
	0:  "DEM_Stop",
	1:  "DEM_FileHeader",
	2:  "DEM_FileInfo",
	3:  "DEM_SyncTick",
	4:  "DEM_SendTables",
	5:  "DEM_ClassInfo",
	6:  "DEM_StringTables",
	7:  "DEM_Packet",
	8:  "DEM_SignonPacket",
	9:  "DEM_ConsoleCmd",
	10: "DEM_CustomData",
	11: "DEM_CustomDataCallbacks",
	12: "DEM_UserCmd",
	13: "DEM_FullPacket",
	14: "DEM_SaveGame",
	15: "DEM_SpawnGroups",
	16: "DEM_Max",
	64: "DEM_IsCompressed",
}
var EDemoCommands_value = map[string]int32{
	"DEM_Error":               -1,
	"DEM_Stop":                0,
	"DEM_FileHeader":          1,
	"DEM_FileInfo":            2,
	"DEM_SyncTick":            3,
	"DEM_SendTables":          4,
	"DEM_ClassInfo":           5,
	"DEM_StringTables":        6,
	"DEM_Packet":              7,
	"DEM_SignonPacket":        8,
	"DEM_ConsoleCmd":          9,
	"DEM_CustomData":          10,
	"DEM_CustomDataCallbacks": 11,
	"DEM_UserCmd":             12,
	"DEM_FullPacket":          13,
	"DEM_SaveGame":            14,
	"DEM_SpawnGroups":         15,
	"DEM_Max":                 16,
	"DEM_IsCompressed":        64,
}

func (x EDemoCommands) Enum() *EDemoCommands {
	p := new(EDemoCommands)
	*p = x
	return p
}
func (x EDemoCommands) String() string {
	return proto.EnumName(EDemoCommands_name, int32(x))
}
func (x *EDemoCommands) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EDemoCommands_value, data, "EDemoCommands")
	if err != nil {
		return err
	}
	*x = EDemoCommands(value)
	return nil
}
func (EDemoCommands) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{0}
}

type CDemoFileHeader struct {
	DemoFileStamp            *string  `protobuf:"bytes,1,req,name=demo_file_stamp,json=demoFileStamp" json:"demo_file_stamp,omitempty"`
	NetworkProtocol          *int32   `protobuf:"varint,2,opt,name=network_protocol,json=networkProtocol" json:"network_protocol,omitempty"`
	ServerName               *string  `protobuf:"bytes,3,opt,name=server_name,json=serverName" json:"server_name,omitempty"`
	ClientName               *string  `protobuf:"bytes,4,opt,name=client_name,json=clientName" json:"client_name,omitempty"`
	MapName                  *string  `protobuf:"bytes,5,opt,name=map_name,json=mapName" json:"map_name,omitempty"`
	GameDirectory            *string  `protobuf:"bytes,6,opt,name=game_directory,json=gameDirectory" json:"game_directory,omitempty"`
	FullpacketsVersion       *int32   `protobuf:"varint,7,opt,name=fullpackets_version,json=fullpacketsVersion" json:"fullpackets_version,omitempty"`
	AllowClientsideEntities  *bool    `protobuf:"varint,8,opt,name=allow_clientside_entities,json=allowClientsideEntities" json:"allow_clientside_entities,omitempty"`
	AllowClientsideParticles *bool    `protobuf:"varint,9,opt,name=allow_clientside_particles,json=allowClientsideParticles" json:"allow_clientside_particles,omitempty"`
	Addons                   *string  `protobuf:"bytes,10,opt,name=addons" json:"addons,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *CDemoFileHeader) Reset()         { *m = CDemoFileHeader{} }
func (m *CDemoFileHeader) String() string { return proto.CompactTextString(m) }
func (*CDemoFileHeader) ProtoMessage()    {}
func (*CDemoFileHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{0}
}
func (m *CDemoFileHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoFileHeader.Unmarshal(m, b)
}
func (m *CDemoFileHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoFileHeader.Marshal(b, m, deterministic)
}
func (dst *CDemoFileHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoFileHeader.Merge(dst, src)
}
func (m *CDemoFileHeader) XXX_Size() int {
	return xxx_messageInfo_CDemoFileHeader.Size(m)
}
func (m *CDemoFileHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoFileHeader.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoFileHeader proto.InternalMessageInfo

func (m *CDemoFileHeader) GetDemoFileStamp() string {
	if m != nil && m.DemoFileStamp != nil {
		return *m.DemoFileStamp
	}
	return ""
}

func (m *CDemoFileHeader) GetNetworkProtocol() int32 {
	if m != nil && m.NetworkProtocol != nil {
		return *m.NetworkProtocol
	}
	return 0
}

func (m *CDemoFileHeader) GetServerName() string {
	if m != nil && m.ServerName != nil {
		return *m.ServerName
	}
	return ""
}

func (m *CDemoFileHeader) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

func (m *CDemoFileHeader) GetMapName() string {
	if m != nil && m.MapName != nil {
		return *m.MapName
	}
	return ""
}

func (m *CDemoFileHeader) GetGameDirectory() string {
	if m != nil && m.GameDirectory != nil {
		return *m.GameDirectory
	}
	return ""
}

func (m *CDemoFileHeader) GetFullpacketsVersion() int32 {
	if m != nil && m.FullpacketsVersion != nil {
		return *m.FullpacketsVersion
	}
	return 0
}

func (m *CDemoFileHeader) GetAllowClientsideEntities() bool {
	if m != nil && m.AllowClientsideEntities != nil {
		return *m.AllowClientsideEntities
	}
	return false
}

func (m *CDemoFileHeader) GetAllowClientsideParticles() bool {
	if m != nil && m.AllowClientsideParticles != nil {
		return *m.AllowClientsideParticles
	}
	return false
}

func (m *CDemoFileHeader) GetAddons() string {
	if m != nil && m.Addons != nil {
		return *m.Addons
	}
	return ""
}

type CGameInfo struct {
	Dota                 *CGameInfo_CDotaGameInfo `protobuf:"bytes,4,opt,name=dota" json:"dota,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CGameInfo) Reset()         { *m = CGameInfo{} }
func (m *CGameInfo) String() string { return proto.CompactTextString(m) }
func (*CGameInfo) ProtoMessage()    {}
func (*CGameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{1}
}
func (m *CGameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameInfo.Unmarshal(m, b)
}
func (m *CGameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameInfo.Marshal(b, m, deterministic)
}
func (dst *CGameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameInfo.Merge(dst, src)
}
func (m *CGameInfo) XXX_Size() int {
	return xxx_messageInfo_CGameInfo.Size(m)
}
func (m *CGameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CGameInfo proto.InternalMessageInfo

func (m *CGameInfo) GetDota() *CGameInfo_CDotaGameInfo {
	if m != nil {
		return m.Dota
	}
	return nil
}

type CGameInfo_CDotaGameInfo struct {
	MatchId              *uint64                                     `protobuf:"varint,1,opt,name=match_id,json=matchId" json:"match_id,omitempty"`
	GameMode             *int32                                      `protobuf:"varint,2,opt,name=game_mode,json=gameMode" json:"game_mode,omitempty"`
	GameWinner           *int32                                      `protobuf:"varint,3,opt,name=game_winner,json=gameWinner" json:"game_winner,omitempty"`
	PlayerInfo           []*CGameInfo_CDotaGameInfo_CPlayerInfo      `protobuf:"bytes,4,rep,name=player_info,json=playerInfo" json:"player_info,omitempty"`
	Leagueid             *uint32                                     `protobuf:"varint,5,opt,name=leagueid" json:"leagueid,omitempty"`
	PicksBans            []*CGameInfo_CDotaGameInfo_CHeroSelectEvent `protobuf:"bytes,6,rep,name=picks_bans,json=picksBans" json:"picks_bans,omitempty"`
	RadiantTeamId        *uint32                                     `protobuf:"varint,7,opt,name=radiant_team_id,json=radiantTeamId" json:"radiant_team_id,omitempty"`
	DireTeamId           *uint32                                     `protobuf:"varint,8,opt,name=dire_team_id,json=direTeamId" json:"dire_team_id,omitempty"`
	RadiantTeamTag       *string                                     `protobuf:"bytes,9,opt,name=radiant_team_tag,json=radiantTeamTag" json:"radiant_team_tag,omitempty"`
	DireTeamTag          *string                                     `protobuf:"bytes,10,opt,name=dire_team_tag,json=direTeamTag" json:"dire_team_tag,omitempty"`
	EndTime              *uint32                                     `protobuf:"varint,11,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *CGameInfo_CDotaGameInfo) Reset()         { *m = CGameInfo_CDotaGameInfo{} }
func (m *CGameInfo_CDotaGameInfo) String() string { return proto.CompactTextString(m) }
func (*CGameInfo_CDotaGameInfo) ProtoMessage()    {}
func (*CGameInfo_CDotaGameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{1, 0}
}
func (m *CGameInfo_CDotaGameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameInfo_CDotaGameInfo.Unmarshal(m, b)
}
func (m *CGameInfo_CDotaGameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameInfo_CDotaGameInfo.Marshal(b, m, deterministic)
}
func (dst *CGameInfo_CDotaGameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameInfo_CDotaGameInfo.Merge(dst, src)
}
func (m *CGameInfo_CDotaGameInfo) XXX_Size() int {
	return xxx_messageInfo_CGameInfo_CDotaGameInfo.Size(m)
}
func (m *CGameInfo_CDotaGameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameInfo_CDotaGameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CGameInfo_CDotaGameInfo proto.InternalMessageInfo

func (m *CGameInfo_CDotaGameInfo) GetMatchId() uint64 {
	if m != nil && m.MatchId != nil {
		return *m.MatchId
	}
	return 0
}

func (m *CGameInfo_CDotaGameInfo) GetGameMode() int32 {
	if m != nil && m.GameMode != nil {
		return *m.GameMode
	}
	return 0
}

func (m *CGameInfo_CDotaGameInfo) GetGameWinner() int32 {
	if m != nil && m.GameWinner != nil {
		return *m.GameWinner
	}
	return 0
}

func (m *CGameInfo_CDotaGameInfo) GetPlayerInfo() []*CGameInfo_CDotaGameInfo_CPlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *CGameInfo_CDotaGameInfo) GetLeagueid() uint32 {
	if m != nil && m.Leagueid != nil {
		return *m.Leagueid
	}
	return 0
}

func (m *CGameInfo_CDotaGameInfo) GetPicksBans() []*CGameInfo_CDotaGameInfo_CHeroSelectEvent {
	if m != nil {
		return m.PicksBans
	}
	return nil
}

func (m *CGameInfo_CDotaGameInfo) GetRadiantTeamId() uint32 {
	if m != nil && m.RadiantTeamId != nil {
		return *m.RadiantTeamId
	}
	return 0
}

func (m *CGameInfo_CDotaGameInfo) GetDireTeamId() uint32 {
	if m != nil && m.DireTeamId != nil {
		return *m.DireTeamId
	}
	return 0
}

func (m *CGameInfo_CDotaGameInfo) GetRadiantTeamTag() string {
	if m != nil && m.RadiantTeamTag != nil {
		return *m.RadiantTeamTag
	}
	return ""
}

func (m *CGameInfo_CDotaGameInfo) GetDireTeamTag() string {
	if m != nil && m.DireTeamTag != nil {
		return *m.DireTeamTag
	}
	return ""
}

func (m *CGameInfo_CDotaGameInfo) GetEndTime() uint32 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type CGameInfo_CDotaGameInfo_CPlayerInfo struct {
	HeroName             *string  `protobuf:"bytes,1,opt,name=hero_name,json=heroName" json:"hero_name,omitempty"`
	PlayerName           *string  `protobuf:"bytes,2,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	IsFakeClient         *bool    `protobuf:"varint,3,opt,name=is_fake_client,json=isFakeClient" json:"is_fake_client,omitempty"`
	Steamid              *uint64  `protobuf:"varint,4,opt,name=steamid" json:"steamid,omitempty"`
	GameTeam             *int32   `protobuf:"varint,5,opt,name=game_team,json=gameTeam" json:"game_team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CGameInfo_CDotaGameInfo_CPlayerInfo) Reset()         { *m = CGameInfo_CDotaGameInfo_CPlayerInfo{} }
func (m *CGameInfo_CDotaGameInfo_CPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*CGameInfo_CDotaGameInfo_CPlayerInfo) ProtoMessage()    {}
func (*CGameInfo_CDotaGameInfo_CPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{1, 0, 0}
}
func (m *CGameInfo_CDotaGameInfo_CPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameInfo_CDotaGameInfo_CPlayerInfo.Unmarshal(m, b)
}
func (m *CGameInfo_CDotaGameInfo_CPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameInfo_CDotaGameInfo_CPlayerInfo.Marshal(b, m, deterministic)
}
func (dst *CGameInfo_CDotaGameInfo_CPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameInfo_CDotaGameInfo_CPlayerInfo.Merge(dst, src)
}
func (m *CGameInfo_CDotaGameInfo_CPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_CGameInfo_CDotaGameInfo_CPlayerInfo.Size(m)
}
func (m *CGameInfo_CDotaGameInfo_CPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameInfo_CDotaGameInfo_CPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CGameInfo_CDotaGameInfo_CPlayerInfo proto.InternalMessageInfo

func (m *CGameInfo_CDotaGameInfo_CPlayerInfo) GetHeroName() string {
	if m != nil && m.HeroName != nil {
		return *m.HeroName
	}
	return ""
}

func (m *CGameInfo_CDotaGameInfo_CPlayerInfo) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *CGameInfo_CDotaGameInfo_CPlayerInfo) GetIsFakeClient() bool {
	if m != nil && m.IsFakeClient != nil {
		return *m.IsFakeClient
	}
	return false
}

func (m *CGameInfo_CDotaGameInfo_CPlayerInfo) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CGameInfo_CDotaGameInfo_CPlayerInfo) GetGameTeam() int32 {
	if m != nil && m.GameTeam != nil {
		return *m.GameTeam
	}
	return 0
}

type CGameInfo_CDotaGameInfo_CHeroSelectEvent struct {
	IsPick               *bool    `protobuf:"varint,1,opt,name=is_pick,json=isPick" json:"is_pick,omitempty"`
	Team                 *uint32  `protobuf:"varint,2,opt,name=team" json:"team,omitempty"`
	HeroId               *uint32  `protobuf:"varint,3,opt,name=hero_id,json=heroId" json:"hero_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CGameInfo_CDotaGameInfo_CHeroSelectEvent) Reset() {
	*m = CGameInfo_CDotaGameInfo_CHeroSelectEvent{}
}
func (m *CGameInfo_CDotaGameInfo_CHeroSelectEvent) String() string { return proto.CompactTextString(m) }
func (*CGameInfo_CDotaGameInfo_CHeroSelectEvent) ProtoMessage()    {}
func (*CGameInfo_CDotaGameInfo_CHeroSelectEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{1, 0, 1}
}
func (m *CGameInfo_CDotaGameInfo_CHeroSelectEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameInfo_CDotaGameInfo_CHeroSelectEvent.Unmarshal(m, b)
}
func (m *CGameInfo_CDotaGameInfo_CHeroSelectEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameInfo_CDotaGameInfo_CHeroSelectEvent.Marshal(b, m, deterministic)
}
func (dst *CGameInfo_CDotaGameInfo_CHeroSelectEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameInfo_CDotaGameInfo_CHeroSelectEvent.Merge(dst, src)
}
func (m *CGameInfo_CDotaGameInfo_CHeroSelectEvent) XXX_Size() int {
	return xxx_messageInfo_CGameInfo_CDotaGameInfo_CHeroSelectEvent.Size(m)
}
func (m *CGameInfo_CDotaGameInfo_CHeroSelectEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameInfo_CDotaGameInfo_CHeroSelectEvent.DiscardUnknown(m)
}

var xxx_messageInfo_CGameInfo_CDotaGameInfo_CHeroSelectEvent proto.InternalMessageInfo

func (m *CGameInfo_CDotaGameInfo_CHeroSelectEvent) GetIsPick() bool {
	if m != nil && m.IsPick != nil {
		return *m.IsPick
	}
	return false
}

func (m *CGameInfo_CDotaGameInfo_CHeroSelectEvent) GetTeam() uint32 {
	if m != nil && m.Team != nil {
		return *m.Team
	}
	return 0
}

func (m *CGameInfo_CDotaGameInfo_CHeroSelectEvent) GetHeroId() uint32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

type CDemoFileInfo struct {
	PlaybackTime         *float32   `protobuf:"fixed32,1,opt,name=playback_time,json=playbackTime" json:"playback_time,omitempty"`
	PlaybackTicks        *int32     `protobuf:"varint,2,opt,name=playback_ticks,json=playbackTicks" json:"playback_ticks,omitempty"`
	PlaybackFrames       *int32     `protobuf:"varint,3,opt,name=playback_frames,json=playbackFrames" json:"playback_frames,omitempty"`
	GameInfo             *CGameInfo `protobuf:"bytes,4,opt,name=game_info,json=gameInfo" json:"game_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CDemoFileInfo) Reset()         { *m = CDemoFileInfo{} }
func (m *CDemoFileInfo) String() string { return proto.CompactTextString(m) }
func (*CDemoFileInfo) ProtoMessage()    {}
func (*CDemoFileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{2}
}
func (m *CDemoFileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoFileInfo.Unmarshal(m, b)
}
func (m *CDemoFileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoFileInfo.Marshal(b, m, deterministic)
}
func (dst *CDemoFileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoFileInfo.Merge(dst, src)
}
func (m *CDemoFileInfo) XXX_Size() int {
	return xxx_messageInfo_CDemoFileInfo.Size(m)
}
func (m *CDemoFileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoFileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoFileInfo proto.InternalMessageInfo

func (m *CDemoFileInfo) GetPlaybackTime() float32 {
	if m != nil && m.PlaybackTime != nil {
		return *m.PlaybackTime
	}
	return 0
}

func (m *CDemoFileInfo) GetPlaybackTicks() int32 {
	if m != nil && m.PlaybackTicks != nil {
		return *m.PlaybackTicks
	}
	return 0
}

func (m *CDemoFileInfo) GetPlaybackFrames() int32 {
	if m != nil && m.PlaybackFrames != nil {
		return *m.PlaybackFrames
	}
	return 0
}

func (m *CDemoFileInfo) GetGameInfo() *CGameInfo {
	if m != nil {
		return m.GameInfo
	}
	return nil
}

type CDemoPacket struct {
	Data                 []byte   `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDemoPacket) Reset()         { *m = CDemoPacket{} }
func (m *CDemoPacket) String() string { return proto.CompactTextString(m) }
func (*CDemoPacket) ProtoMessage()    {}
func (*CDemoPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{3}
}
func (m *CDemoPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoPacket.Unmarshal(m, b)
}
func (m *CDemoPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoPacket.Marshal(b, m, deterministic)
}
func (dst *CDemoPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoPacket.Merge(dst, src)
}
func (m *CDemoPacket) XXX_Size() int {
	return xxx_messageInfo_CDemoPacket.Size(m)
}
func (m *CDemoPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoPacket.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoPacket proto.InternalMessageInfo

func (m *CDemoPacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CDemoFullPacket struct {
	StringTable          *CDemoStringTables `protobuf:"bytes,1,opt,name=string_table,json=stringTable" json:"string_table,omitempty"`
	Packet               *CDemoPacket       `protobuf:"bytes,2,opt,name=packet" json:"packet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CDemoFullPacket) Reset()         { *m = CDemoFullPacket{} }
func (m *CDemoFullPacket) String() string { return proto.CompactTextString(m) }
func (*CDemoFullPacket) ProtoMessage()    {}
func (*CDemoFullPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{4}
}
func (m *CDemoFullPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoFullPacket.Unmarshal(m, b)
}
func (m *CDemoFullPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoFullPacket.Marshal(b, m, deterministic)
}
func (dst *CDemoFullPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoFullPacket.Merge(dst, src)
}
func (m *CDemoFullPacket) XXX_Size() int {
	return xxx_messageInfo_CDemoFullPacket.Size(m)
}
func (m *CDemoFullPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoFullPacket.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoFullPacket proto.InternalMessageInfo

func (m *CDemoFullPacket) GetStringTable() *CDemoStringTables {
	if m != nil {
		return m.StringTable
	}
	return nil
}

func (m *CDemoFullPacket) GetPacket() *CDemoPacket {
	if m != nil {
		return m.Packet
	}
	return nil
}

type CDemoSaveGame struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	SteamId              *uint64  `protobuf:"fixed64,2,opt,name=steam_id,json=steamId" json:"steam_id,omitempty"`
	Signature            *uint64  `protobuf:"fixed64,3,opt,name=signature" json:"signature,omitempty"`
	Version              *int32   `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDemoSaveGame) Reset()         { *m = CDemoSaveGame{} }
func (m *CDemoSaveGame) String() string { return proto.CompactTextString(m) }
func (*CDemoSaveGame) ProtoMessage()    {}
func (*CDemoSaveGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{5}
}
func (m *CDemoSaveGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoSaveGame.Unmarshal(m, b)
}
func (m *CDemoSaveGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoSaveGame.Marshal(b, m, deterministic)
}
func (dst *CDemoSaveGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoSaveGame.Merge(dst, src)
}
func (m *CDemoSaveGame) XXX_Size() int {
	return xxx_messageInfo_CDemoSaveGame.Size(m)
}
func (m *CDemoSaveGame) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoSaveGame.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoSaveGame proto.InternalMessageInfo

func (m *CDemoSaveGame) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CDemoSaveGame) GetSteamId() uint64 {
	if m != nil && m.SteamId != nil {
		return *m.SteamId
	}
	return 0
}

func (m *CDemoSaveGame) GetSignature() uint64 {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return 0
}

func (m *CDemoSaveGame) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type CDemoSyncTick struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDemoSyncTick) Reset()         { *m = CDemoSyncTick{} }
func (m *CDemoSyncTick) String() string { return proto.CompactTextString(m) }
func (*CDemoSyncTick) ProtoMessage()    {}
func (*CDemoSyncTick) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{6}
}
func (m *CDemoSyncTick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoSyncTick.Unmarshal(m, b)
}
func (m *CDemoSyncTick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoSyncTick.Marshal(b, m, deterministic)
}
func (dst *CDemoSyncTick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoSyncTick.Merge(dst, src)
}
func (m *CDemoSyncTick) XXX_Size() int {
	return xxx_messageInfo_CDemoSyncTick.Size(m)
}
func (m *CDemoSyncTick) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoSyncTick.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoSyncTick proto.InternalMessageInfo

type CDemoConsoleCmd struct {
	Cmdstring            *string  `protobuf:"bytes,1,opt,name=cmdstring" json:"cmdstring,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDemoConsoleCmd) Reset()         { *m = CDemoConsoleCmd{} }
func (m *CDemoConsoleCmd) String() string { return proto.CompactTextString(m) }
func (*CDemoConsoleCmd) ProtoMessage()    {}
func (*CDemoConsoleCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{7}
}
func (m *CDemoConsoleCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoConsoleCmd.Unmarshal(m, b)
}
func (m *CDemoConsoleCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoConsoleCmd.Marshal(b, m, deterministic)
}
func (dst *CDemoConsoleCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoConsoleCmd.Merge(dst, src)
}
func (m *CDemoConsoleCmd) XXX_Size() int {
	return xxx_messageInfo_CDemoConsoleCmd.Size(m)
}
func (m *CDemoConsoleCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoConsoleCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoConsoleCmd proto.InternalMessageInfo

func (m *CDemoConsoleCmd) GetCmdstring() string {
	if m != nil && m.Cmdstring != nil {
		return *m.Cmdstring
	}
	return ""
}

type CDemoSendTables struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDemoSendTables) Reset()         { *m = CDemoSendTables{} }
func (m *CDemoSendTables) String() string { return proto.CompactTextString(m) }
func (*CDemoSendTables) ProtoMessage()    {}
func (*CDemoSendTables) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{8}
}
func (m *CDemoSendTables) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoSendTables.Unmarshal(m, b)
}
func (m *CDemoSendTables) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoSendTables.Marshal(b, m, deterministic)
}
func (dst *CDemoSendTables) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoSendTables.Merge(dst, src)
}
func (m *CDemoSendTables) XXX_Size() int {
	return xxx_messageInfo_CDemoSendTables.Size(m)
}
func (m *CDemoSendTables) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoSendTables.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoSendTables proto.InternalMessageInfo

func (m *CDemoSendTables) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CDemoClassInfo struct {
	Classes              []*CDemoClassInfoClassT `protobuf:"bytes,1,rep,name=classes" json:"classes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CDemoClassInfo) Reset()         { *m = CDemoClassInfo{} }
func (m *CDemoClassInfo) String() string { return proto.CompactTextString(m) }
func (*CDemoClassInfo) ProtoMessage()    {}
func (*CDemoClassInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{9}
}
func (m *CDemoClassInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoClassInfo.Unmarshal(m, b)
}
func (m *CDemoClassInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoClassInfo.Marshal(b, m, deterministic)
}
func (dst *CDemoClassInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoClassInfo.Merge(dst, src)
}
func (m *CDemoClassInfo) XXX_Size() int {
	return xxx_messageInfo_CDemoClassInfo.Size(m)
}
func (m *CDemoClassInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoClassInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoClassInfo proto.InternalMessageInfo

func (m *CDemoClassInfo) GetClasses() []*CDemoClassInfoClassT {
	if m != nil {
		return m.Classes
	}
	return nil
}

type CDemoClassInfoClassT struct {
	ClassId              *int32   `protobuf:"varint,1,opt,name=class_id,json=classId" json:"class_id,omitempty"`
	NetworkName          *string  `protobuf:"bytes,2,opt,name=network_name,json=networkName" json:"network_name,omitempty"`
	TableName            *string  `protobuf:"bytes,3,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDemoClassInfoClassT) Reset()         { *m = CDemoClassInfoClassT{} }
func (m *CDemoClassInfoClassT) String() string { return proto.CompactTextString(m) }
func (*CDemoClassInfoClassT) ProtoMessage()    {}
func (*CDemoClassInfoClassT) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{9, 0}
}
func (m *CDemoClassInfoClassT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoClassInfoClassT.Unmarshal(m, b)
}
func (m *CDemoClassInfoClassT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoClassInfoClassT.Marshal(b, m, deterministic)
}
func (dst *CDemoClassInfoClassT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoClassInfoClassT.Merge(dst, src)
}
func (m *CDemoClassInfoClassT) XXX_Size() int {
	return xxx_messageInfo_CDemoClassInfoClassT.Size(m)
}
func (m *CDemoClassInfoClassT) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoClassInfoClassT.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoClassInfoClassT proto.InternalMessageInfo

func (m *CDemoClassInfoClassT) GetClassId() int32 {
	if m != nil && m.ClassId != nil {
		return *m.ClassId
	}
	return 0
}

func (m *CDemoClassInfoClassT) GetNetworkName() string {
	if m != nil && m.NetworkName != nil {
		return *m.NetworkName
	}
	return ""
}

func (m *CDemoClassInfoClassT) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

type CDemoCustomData struct {
	CallbackIndex        *int32   `protobuf:"varint,1,opt,name=callback_index,json=callbackIndex" json:"callback_index,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDemoCustomData) Reset()         { *m = CDemoCustomData{} }
func (m *CDemoCustomData) String() string { return proto.CompactTextString(m) }
func (*CDemoCustomData) ProtoMessage()    {}
func (*CDemoCustomData) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{10}
}
func (m *CDemoCustomData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoCustomData.Unmarshal(m, b)
}
func (m *CDemoCustomData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoCustomData.Marshal(b, m, deterministic)
}
func (dst *CDemoCustomData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoCustomData.Merge(dst, src)
}
func (m *CDemoCustomData) XXX_Size() int {
	return xxx_messageInfo_CDemoCustomData.Size(m)
}
func (m *CDemoCustomData) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoCustomData.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoCustomData proto.InternalMessageInfo

func (m *CDemoCustomData) GetCallbackIndex() int32 {
	if m != nil && m.CallbackIndex != nil {
		return *m.CallbackIndex
	}
	return 0
}

func (m *CDemoCustomData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CDemoCustomDataCallbacks struct {
	SaveId               []string `protobuf:"bytes,1,rep,name=save_id,json=saveId" json:"save_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDemoCustomDataCallbacks) Reset()         { *m = CDemoCustomDataCallbacks{} }
func (m *CDemoCustomDataCallbacks) String() string { return proto.CompactTextString(m) }
func (*CDemoCustomDataCallbacks) ProtoMessage()    {}
func (*CDemoCustomDataCallbacks) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{11}
}
func (m *CDemoCustomDataCallbacks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoCustomDataCallbacks.Unmarshal(m, b)
}
func (m *CDemoCustomDataCallbacks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoCustomDataCallbacks.Marshal(b, m, deterministic)
}
func (dst *CDemoCustomDataCallbacks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoCustomDataCallbacks.Merge(dst, src)
}
func (m *CDemoCustomDataCallbacks) XXX_Size() int {
	return xxx_messageInfo_CDemoCustomDataCallbacks.Size(m)
}
func (m *CDemoCustomDataCallbacks) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoCustomDataCallbacks.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoCustomDataCallbacks proto.InternalMessageInfo

func (m *CDemoCustomDataCallbacks) GetSaveId() []string {
	if m != nil {
		return m.SaveId
	}
	return nil
}

type CDemoStringTables struct {
	Tables               []*CDemoStringTablesTableT `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CDemoStringTables) Reset()         { *m = CDemoStringTables{} }
func (m *CDemoStringTables) String() string { return proto.CompactTextString(m) }
func (*CDemoStringTables) ProtoMessage()    {}
func (*CDemoStringTables) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{12}
}
func (m *CDemoStringTables) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoStringTables.Unmarshal(m, b)
}
func (m *CDemoStringTables) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoStringTables.Marshal(b, m, deterministic)
}
func (dst *CDemoStringTables) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoStringTables.Merge(dst, src)
}
func (m *CDemoStringTables) XXX_Size() int {
	return xxx_messageInfo_CDemoStringTables.Size(m)
}
func (m *CDemoStringTables) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoStringTables.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoStringTables proto.InternalMessageInfo

func (m *CDemoStringTables) GetTables() []*CDemoStringTablesTableT {
	if m != nil {
		return m.Tables
	}
	return nil
}

type CDemoStringTablesItemsT struct {
	Str                  *string  `protobuf:"bytes,1,opt,name=str" json:"str,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDemoStringTablesItemsT) Reset()         { *m = CDemoStringTablesItemsT{} }
func (m *CDemoStringTablesItemsT) String() string { return proto.CompactTextString(m) }
func (*CDemoStringTablesItemsT) ProtoMessage()    {}
func (*CDemoStringTablesItemsT) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{12, 0}
}
func (m *CDemoStringTablesItemsT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoStringTablesItemsT.Unmarshal(m, b)
}
func (m *CDemoStringTablesItemsT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoStringTablesItemsT.Marshal(b, m, deterministic)
}
func (dst *CDemoStringTablesItemsT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoStringTablesItemsT.Merge(dst, src)
}
func (m *CDemoStringTablesItemsT) XXX_Size() int {
	return xxx_messageInfo_CDemoStringTablesItemsT.Size(m)
}
func (m *CDemoStringTablesItemsT) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoStringTablesItemsT.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoStringTablesItemsT proto.InternalMessageInfo

func (m *CDemoStringTablesItemsT) GetStr() string {
	if m != nil && m.Str != nil {
		return *m.Str
	}
	return ""
}

func (m *CDemoStringTablesItemsT) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CDemoStringTablesTableT struct {
	TableName            *string                    `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Items                []*CDemoStringTablesItemsT `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	ItemsClientside      []*CDemoStringTablesItemsT `protobuf:"bytes,3,rep,name=items_clientside,json=itemsClientside" json:"items_clientside,omitempty"`
	TableFlags           *int32                     `protobuf:"varint,4,opt,name=table_flags,json=tableFlags" json:"table_flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CDemoStringTablesTableT) Reset()         { *m = CDemoStringTablesTableT{} }
func (m *CDemoStringTablesTableT) String() string { return proto.CompactTextString(m) }
func (*CDemoStringTablesTableT) ProtoMessage()    {}
func (*CDemoStringTablesTableT) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{12, 1}
}
func (m *CDemoStringTablesTableT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoStringTablesTableT.Unmarshal(m, b)
}
func (m *CDemoStringTablesTableT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoStringTablesTableT.Marshal(b, m, deterministic)
}
func (dst *CDemoStringTablesTableT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoStringTablesTableT.Merge(dst, src)
}
func (m *CDemoStringTablesTableT) XXX_Size() int {
	return xxx_messageInfo_CDemoStringTablesTableT.Size(m)
}
func (m *CDemoStringTablesTableT) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoStringTablesTableT.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoStringTablesTableT proto.InternalMessageInfo

func (m *CDemoStringTablesTableT) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *CDemoStringTablesTableT) GetItems() []*CDemoStringTablesItemsT {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *CDemoStringTablesTableT) GetItemsClientside() []*CDemoStringTablesItemsT {
	if m != nil {
		return m.ItemsClientside
	}
	return nil
}

func (m *CDemoStringTablesTableT) GetTableFlags() int32 {
	if m != nil && m.TableFlags != nil {
		return *m.TableFlags
	}
	return 0
}

type CDemoStop struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDemoStop) Reset()         { *m = CDemoStop{} }
func (m *CDemoStop) String() string { return proto.CompactTextString(m) }
func (*CDemoStop) ProtoMessage()    {}
func (*CDemoStop) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{13}
}
func (m *CDemoStop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoStop.Unmarshal(m, b)
}
func (m *CDemoStop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoStop.Marshal(b, m, deterministic)
}
func (dst *CDemoStop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoStop.Merge(dst, src)
}
func (m *CDemoStop) XXX_Size() int {
	return xxx_messageInfo_CDemoStop.Size(m)
}
func (m *CDemoStop) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoStop.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoStop proto.InternalMessageInfo

type CDemoUserCmd struct {
	CmdNumber            *int32   `protobuf:"varint,1,opt,name=cmd_number,json=cmdNumber" json:"cmd_number,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDemoUserCmd) Reset()         { *m = CDemoUserCmd{} }
func (m *CDemoUserCmd) String() string { return proto.CompactTextString(m) }
func (*CDemoUserCmd) ProtoMessage()    {}
func (*CDemoUserCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{14}
}
func (m *CDemoUserCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoUserCmd.Unmarshal(m, b)
}
func (m *CDemoUserCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoUserCmd.Marshal(b, m, deterministic)
}
func (dst *CDemoUserCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoUserCmd.Merge(dst, src)
}
func (m *CDemoUserCmd) XXX_Size() int {
	return xxx_messageInfo_CDemoUserCmd.Size(m)
}
func (m *CDemoUserCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoUserCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoUserCmd proto.InternalMessageInfo

func (m *CDemoUserCmd) GetCmdNumber() int32 {
	if m != nil && m.CmdNumber != nil {
		return *m.CmdNumber
	}
	return 0
}

func (m *CDemoUserCmd) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CDemoSpawnGroups struct {
	Msgs                 [][]byte `protobuf:"bytes,3,rep,name=msgs" json:"msgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDemoSpawnGroups) Reset()         { *m = CDemoSpawnGroups{} }
func (m *CDemoSpawnGroups) String() string { return proto.CompactTextString(m) }
func (*CDemoSpawnGroups) ProtoMessage()    {}
func (*CDemoSpawnGroups) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_99169cde9e52ae32, []int{15}
}
func (m *CDemoSpawnGroups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDemoSpawnGroups.Unmarshal(m, b)
}
func (m *CDemoSpawnGroups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDemoSpawnGroups.Marshal(b, m, deterministic)
}
func (dst *CDemoSpawnGroups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDemoSpawnGroups.Merge(dst, src)
}
func (m *CDemoSpawnGroups) XXX_Size() int {
	return xxx_messageInfo_CDemoSpawnGroups.Size(m)
}
func (m *CDemoSpawnGroups) XXX_DiscardUnknown() {
	xxx_messageInfo_CDemoSpawnGroups.DiscardUnknown(m)
}

var xxx_messageInfo_CDemoSpawnGroups proto.InternalMessageInfo

func (m *CDemoSpawnGroups) GetMsgs() [][]byte {
	if m != nil {
		return m.Msgs
	}
	return nil
}

func init() {
	proto.RegisterType((*CDemoFileHeader)(nil), "CDemoFileHeader")
	proto.RegisterType((*CGameInfo)(nil), "CGameInfo")
	proto.RegisterType((*CGameInfo_CDotaGameInfo)(nil), "CGameInfo.CDotaGameInfo")
	proto.RegisterType((*CGameInfo_CDotaGameInfo_CPlayerInfo)(nil), "CGameInfo.CDotaGameInfo.CPlayerInfo")
	proto.RegisterType((*CGameInfo_CDotaGameInfo_CHeroSelectEvent)(nil), "CGameInfo.CDotaGameInfo.CHeroSelectEvent")
	proto.RegisterType((*CDemoFileInfo)(nil), "CDemoFileInfo")
	proto.RegisterType((*CDemoPacket)(nil), "CDemoPacket")
	proto.RegisterType((*CDemoFullPacket)(nil), "CDemoFullPacket")
	proto.RegisterType((*CDemoSaveGame)(nil), "CDemoSaveGame")
	proto.RegisterType((*CDemoSyncTick)(nil), "CDemoSyncTick")
	proto.RegisterType((*CDemoConsoleCmd)(nil), "CDemoConsoleCmd")
	proto.RegisterType((*CDemoSendTables)(nil), "CDemoSendTables")
	proto.RegisterType((*CDemoClassInfo)(nil), "CDemoClassInfo")
	proto.RegisterType((*CDemoClassInfoClassT)(nil), "CDemoClassInfo.class_t")
	proto.RegisterType((*CDemoCustomData)(nil), "CDemoCustomData")
	proto.RegisterType((*CDemoCustomDataCallbacks)(nil), "CDemoCustomDataCallbacks")
	proto.RegisterType((*CDemoStringTables)(nil), "CDemoStringTables")
	proto.RegisterType((*CDemoStringTablesItemsT)(nil), "CDemoStringTables.items_t")
	proto.RegisterType((*CDemoStringTablesTableT)(nil), "CDemoStringTables.table_t")
	proto.RegisterType((*CDemoStop)(nil), "CDemoStop")
	proto.RegisterType((*CDemoUserCmd)(nil), "CDemoUserCmd")
	proto.RegisterType((*CDemoSpawnGroups)(nil), "CDemoSpawnGroups")
	proto.RegisterEnum("EDemoCommands", EDemoCommands_name, EDemoCommands_value)
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_demo_99169cde9e52ae32) }

var fileDescriptor_demo_99169cde9e52ae32 = []byte{
	// 1359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x56, 0xcb, 0x6e, 0xdb, 0x46,
	0x17, 0x0e, 0x25, 0x59, 0x97, 0x43, 0x5d, 0x98, 0xc9, 0x8f, 0xdf, 0x8c, 0xd2, 0xa0, 0x0e, 0x9b,
	0x8b, 0x53, 0x14, 0x4a, 0xeb, 0xa2, 0x9b, 0xa2, 0x8b, 0x36, 0xb2, 0x9d, 0x08, 0x68, 0x02, 0x83,
	0x76, 0x2f, 0x3b, 0x62, 0x4c, 0x8e, 0x94, 0x81, 0x78, 0x11, 0x38, 0x23, 0x3b, 0xd9, 0x75, 0xd1,
	0x4d, 0xdf, 0xa4, 0x40, 0xd0, 0x47, 0xe8, 0xa6, 0xfb, 0x3e, 0x53, 0x8b, 0x73, 0x66, 0x48, 0xc9,
	0x4e, 0x82, 0x6a, 0x35, 0xf3, 0x9d, 0x6f, 0xce, 0x9c, 0xcb, 0x37, 0x87, 0x02, 0x48, 0x44, 0x56,
	0x4c, 0x56, 0x65, 0xa1, 0x8b, 0xe0, 0x6d, 0x13, 0x46, 0xd3, 0x43, 0x91, 0x15, 0xc7, 0x32, 0x15,
	0xcf, 0x05, 0x4f, 0x44, 0xc9, 0x1e, 0xc2, 0x08, 0x19, 0xd1, 0x5c, 0xa6, 0x22, 0x52, 0x9a, 0x67,
	0x2b, 0xdf, 0xd9, 0x6b, 0xec, 0xf7, 0xc2, 0x41, 0x62, 0x89, 0xa7, 0x08, 0xb2, 0xc7, 0xe0, 0xe5,
	0x42, 0x5f, 0x16, 0xe5, 0x32, 0x22, 0x67, 0x71, 0x91, 0xfa, 0x8d, 0x3d, 0x67, 0x7f, 0x27, 0x1c,
	0x59, 0xfc, 0xc4, 0xc2, 0xec, 0x63, 0x70, 0x95, 0x28, 0x2f, 0x44, 0x19, 0xe5, 0x3c, 0x13, 0x7e,
	0x73, 0xcf, 0xd9, 0xef, 0x85, 0x60, 0xa0, 0x97, 0x3c, 0x13, 0x48, 0x88, 0x53, 0x29, 0x72, 0x6d,
	0x08, 0x2d, 0x43, 0x30, 0x10, 0x11, 0x6e, 0x43, 0x37, 0xe3, 0x2b, 0x63, 0xdd, 0x21, 0x6b, 0x27,
	0xe3, 0x2b, 0x32, 0x3d, 0x80, 0xe1, 0x82, 0x67, 0x22, 0x4a, 0x64, 0x29, 0x62, 0x5d, 0x94, 0x6f,
	0xfc, 0x36, 0x11, 0x06, 0x88, 0x1e, 0x56, 0x20, 0x7b, 0x02, 0xb7, 0xe6, 0xeb, 0x34, 0x5d, 0xf1,
	0x78, 0x29, 0xb4, 0x8a, 0x2e, 0x44, 0xa9, 0x64, 0x91, 0xfb, 0x1d, 0x8a, 0x98, 0x6d, 0x99, 0x7e,
	0x34, 0x16, 0xf6, 0x35, 0xdc, 0xe6, 0x69, 0x5a, 0x5c, 0x46, 0x26, 0x0c, 0x25, 0x13, 0x11, 0x89,
	0x5c, 0x4b, 0x2d, 0x85, 0xf2, 0xbb, 0x7b, 0xce, 0x7e, 0x37, 0xdc, 0x25, 0xc2, 0xb4, 0xb6, 0x1f,
	0x59, 0x33, 0xfb, 0x06, 0xc6, 0xef, 0x9c, 0x5d, 0xf1, 0x52, 0xcb, 0x38, 0x15, 0xca, 0xef, 0xd1,
	0x61, 0xff, 0xda, 0xe1, 0x93, 0xca, 0xce, 0xfe, 0x0f, 0x6d, 0x9e, 0x24, 0x45, 0xae, 0x7c, 0xa0,
	0x4c, 0xec, 0x2e, 0xf8, 0xad, 0x0d, 0xbd, 0xe9, 0x33, 0x9e, 0x89, 0x59, 0x3e, 0x2f, 0xd8, 0x67,
	0xd0, 0x4a, 0x0a, 0xcd, 0xa9, 0x58, 0xee, 0x81, 0x3f, 0xa9, 0x2d, 0x93, 0xe9, 0x61, 0xa1, 0x79,
	0xb5, 0x0b, 0x89, 0x35, 0xfe, 0x7b, 0x07, 0x06, 0x57, 0x70, 0x53, 0x52, 0x1d, 0xbf, 0x8a, 0x64,
	0xe2, 0x3b, 0x7b, 0xce, 0x7e, 0x0b, 0x4b, 0xaa, 0xe3, 0x57, 0xb3, 0x84, 0xdd, 0x81, 0x1e, 0x95,
	0x34, 0x2b, 0x12, 0x61, 0x7b, 0xda, 0x45, 0xe0, 0x45, 0x91, 0x50, 0xaf, 0xc8, 0x78, 0x29, 0xf3,
	0x5c, 0x94, 0xd4, 0xcc, 0x9d, 0x10, 0x10, 0xfa, 0x89, 0x10, 0x76, 0x04, 0xee, 0x2a, 0xe5, 0x6f,
	0x44, 0x19, 0xc9, 0x7c, 0x5e, 0xf8, 0xad, 0xbd, 0xe6, 0xbe, 0x7b, 0x70, 0xff, 0x43, 0xf1, 0x4d,
	0xa6, 0x27, 0x44, 0xa6, 0x58, 0x61, 0x55, 0xaf, 0xd9, 0x18, 0xba, 0xa9, 0xe0, 0x8b, 0xb5, 0x90,
	0x09, 0xb5, 0x7c, 0x10, 0xd6, 0x7b, 0xf6, 0x1c, 0x60, 0x25, 0xe3, 0xa5, 0x8a, 0xce, 0x79, 0xae,
	0xfc, 0x36, 0xdd, 0xf0, 0xf8, 0xc3, 0x37, 0x3c, 0x17, 0x65, 0x71, 0x2a, 0x52, 0x11, 0xeb, 0xa3,
	0x0b, 0x91, 0xeb, 0xb0, 0x47, 0x87, 0x9f, 0xf2, 0x5c, 0xa1, 0xda, 0x4b, 0x9e, 0x48, 0x9e, 0xeb,
	0x48, 0x0b, 0x9e, 0x61, 0x31, 0x3a, 0x74, 0xd9, 0xc0, 0xc2, 0x67, 0x82, 0x67, 0xb3, 0x84, 0xed,
	0x41, 0x1f, 0x05, 0x56, 0x93, 0xba, 0x44, 0x02, 0xc4, 0x2c, 0x63, 0x1f, 0xbc, 0x2b, 0x9e, 0x34,
	0x5f, 0x50, 0xa7, 0x7b, 0xe1, 0x70, 0xcb, 0xd5, 0x19, 0x5f, 0xb0, 0x00, 0x06, 0x1b, 0x5f, 0x48,
	0x33, 0x6d, 0x76, 0x2b, 0x67, 0xc8, 0xb9, 0x0d, 0x5d, 0x91, 0x27, 0x91, 0x96, 0x99, 0xf0, 0x5d,
	0xba, 0xab, 0x23, 0xf2, 0xe4, 0x4c, 0x66, 0x62, 0xfc, 0xbb, 0x03, 0xee, 0x56, 0xd1, 0xb0, 0x5b,
	0xaf, 0x44, 0x59, 0x98, 0xc7, 0xe1, 0x90, 0xab, 0x2e, 0x02, 0xd5, 0xcb, 0xb2, 0xcd, 0x20, 0x73,
	0xc3, 0xbc, 0x2c, 0x03, 0x11, 0xe1, 0x3e, 0x0c, 0xa5, 0x8a, 0xe6, 0x7c, 0x29, 0xac, 0x58, 0xa9,
	0xa3, 0xdd, 0xb0, 0x2f, 0xd5, 0x31, 0x5f, 0x0a, 0xa3, 0x4f, 0xe6, 0x43, 0x47, 0x61, 0xb8, 0x32,
	0x21, 0xbd, 0xb5, 0xc2, 0x6a, 0x5b, 0x6b, 0x05, 0xb7, 0xd4, 0x27, 0xab, 0x15, 0x4c, 0x64, 0xfc,
	0x33, 0x78, 0xd7, 0x8b, 0xcf, 0x76, 0xa1, 0x23, 0x55, 0x84, 0x1d, 0xa0, 0x60, 0xbb, 0x61, 0x5b,
	0xaa, 0x13, 0x19, 0x2f, 0x19, 0x83, 0x16, 0x39, 0x69, 0x50, 0xba, 0xb4, 0x46, 0x32, 0xe5, 0x26,
	0x13, 0x0a, 0x6b, 0x10, 0xb6, 0x71, 0x3b, 0x4b, 0x82, 0x3f, 0x1c, 0xd4, 0xb3, 0x1d, 0x48, 0x54,
	0x86, 0x4f, 0x60, 0x80, 0x69, 0x9d, 0xf3, 0x78, 0x69, 0xca, 0x86, 0xde, 0x1b, 0x61, 0xbf, 0x02,
	0xb1, 0x76, 0x38, 0x2c, 0xb6, 0x48, 0xf1, 0x52, 0x59, 0x79, 0x0f, 0x36, 0xac, 0x78, 0xa9, 0xd8,
	0x23, 0x18, 0xd5, 0xb4, 0x79, 0xc9, 0x33, 0xa1, 0xac, 0xce, 0xeb, 0xd3, 0xc7, 0x84, 0xb2, 0x47,
	0x36, 0x7b, 0xab, 0x74, 0x7c, 0x89, 0xb0, 0xd1, 0xa1, 0xa9, 0x04, 0xae, 0x82, 0x7b, 0xe0, 0x52,
	0xb8, 0x27, 0x34, 0x64, 0x30, 0xd7, 0x84, 0x6b, 0x4e, 0x5e, 0xfb, 0x21, 0xad, 0x83, 0xbc, 0x9a,
	0xc5, 0xeb, 0x34, 0xb5, 0xb4, 0xaf, 0xa0, 0xaf, 0x74, 0x29, 0xf3, 0x45, 0xa4, 0xf9, 0x79, 0x6a,
	0x52, 0x72, 0x0f, 0xd8, 0x84, 0x78, 0xa7, 0x64, 0x39, 0x43, 0x83, 0x0a, 0x5d, 0xb5, 0xd9, 0xb1,
	0xfb, 0xd0, 0x36, 0xc3, 0x8c, 0xb2, 0x73, 0x0f, 0xfa, 0x93, 0xad, 0xbb, 0x43, 0x6b, 0x0b, 0x2e,
	0x6c, 0x05, 0x4f, 0xf9, 0x85, 0xc0, 0x88, 0xeb, 0xa0, 0x9c, 0x4d, 0x50, 0xa8, 0x43, 0x55, 0x69,
	0x1e, 0x9d, 0xb5, 0x6d, 0xe7, 0x67, 0x09, 0xfb, 0x08, 0x7a, 0x4a, 0x2e, 0x72, 0xae, 0xd7, 0xa5,
	0x99, 0xe9, 0xed, 0x70, 0x03, 0xa0, 0x62, 0xaa, 0x19, 0xdb, 0xa2, 0xd2, 0x55, 0xdb, 0x60, 0x54,
	0xdd, 0xfb, 0x26, 0x8f, 0xb1, 0xdc, 0xc1, 0x13, 0x9b, 0xf8, 0xb4, 0xc8, 0x55, 0x91, 0x8a, 0x69,
	0x46, 0xbe, 0xe3, 0x2c, 0x31, 0x39, 0x59, 0x4d, 0x6f, 0x80, 0xe0, 0x81, 0x3d, 0x70, 0x8a, 0x4f,
	0x82, 0xf2, 0x7f, 0x5f, 0xec, 0xc1, 0x5b, 0x07, 0x86, 0xc6, 0x71, 0xca, 0x95, 0x22, 0x91, 0x7c,
	0x01, 0x9d, 0x18, 0x37, 0x42, 0xf9, 0x0e, 0x4d, 0x8d, 0xdd, 0xc9, 0x55, 0xc6, 0x84, 0xcc, 0x91,
	0x0e, 0x2b, 0xde, 0x78, 0x6e, 0x8f, 0x44, 0x1a, 0x8b, 0x61, 0x96, 0x76, 0x64, 0xee, 0x58, 0xd6,
	0x2c, 0x61, 0xf7, 0xa0, 0x5f, 0x7d, 0x0d, 0xb7, 0x1e, 0x9a, 0x6b, 0x31, 0x7a, 0x69, 0x77, 0x01,
	0xa8, 0x8b, 0xdb, 0x1f, 0xc1, 0x1e, 0x21, 0x68, 0x0e, 0xbe, 0xaf, 0xaa, 0xb0, 0x56, 0xba, 0xc8,
	0x0e, 0xb1, 0xf8, 0x0f, 0x60, 0x18, 0xf3, 0x34, 0x25, 0x19, 0xca, 0x3c, 0x11, 0xaf, 0xed, 0xad,
	0x83, 0x0a, 0x9d, 0x21, 0x58, 0xe7, 0xde, 0xd8, 0xca, 0xfd, 0x4b, 0xf0, 0xaf, 0x79, 0x9b, 0xda,
	0x33, 0x0a, 0x1f, 0x95, 0xe2, 0x17, 0xc2, 0x64, 0xd1, 0xc4, 0x0f, 0x0c, 0x6e, 0x67, 0x49, 0xf0,
	0x67, 0x03, 0x6e, 0xbe, 0x23, 0x2d, 0x76, 0x00, 0x6d, 0x8a, 0xb2, 0x2a, 0xd9, 0xf8, 0x5d, 0xf9,
	0x4d, 0x4c, 0x62, 0x3a, 0xb4, 0xcc, 0xf1, 0x13, 0xe8, 0x48, 0x2d, 0x32, 0x2c, 0x9a, 0x07, 0x4d,
	0xa5, 0x4b, 0xdb, 0x44, 0x5c, 0xbe, 0x2f, 0xde, 0xf1, 0x5f, 0x0e, 0x74, 0xac, 0x93, 0x6b, 0x85,
	0x72, 0xae, 0x15, 0x8a, 0x7d, 0x0e, 0x3b, 0xe4, 0xdb, 0x6f, 0x7c, 0x30, 0x1c, 0x7b, 0x77, 0x68,
	0x88, 0xec, 0x08, 0x3c, 0x83, 0x6c, 0x3e, 0xc7, 0x7e, 0xf3, 0x3f, 0x0f, 0x8f, 0x68, 0xb1, 0xf9,
	0x40, 0xe3, 0x2c, 0x35, 0x71, 0xcd, 0x53, 0xbe, 0x50, 0x56, 0xd6, 0x26, 0xd4, 0x63, 0x44, 0x02,
	0x17, 0x7a, 0xd6, 0x5d, 0xb1, 0x0a, 0xbe, 0x83, 0x3e, 0x6d, 0x7e, 0x50, 0xa2, 0x44, 0x49, 0xdf,
	0x05, 0x88, 0xb3, 0x24, 0xca, 0xd7, 0xd9, 0xb9, 0x28, 0x6d, 0x23, 0x51, 0xd3, 0x2f, 0x09, 0x78,
	0x6f, 0x13, 0x1f, 0x82, 0x67, 0xfc, 0xad, 0xf8, 0x65, 0xfe, 0xac, 0x2c, 0xd6, 0x2b, 0x12, 0x7a,
	0xa6, 0x16, 0x8a, 0xe2, 0xef, 0x87, 0xb4, 0xfe, 0xf4, 0xd7, 0x26, 0x0c, 0x8e, 0xcc, 0x0b, 0xca,
	0x32, 0x9e, 0x27, 0xf8, 0x17, 0xa2, 0x77, 0x78, 0xf4, 0x22, 0x3a, 0x2a, 0xcb, 0xa2, 0xf4, 0xfe,
	0xa9, 0x7e, 0x0e, 0xeb, 0x43, 0x17, 0x71, 0x0c, 0xd0, 0xbb, 0xc1, 0x18, 0x0c, 0x71, 0xb7, 0xf9,
	0xf3, 0xe7, 0x39, 0xcc, 0x83, 0x7e, 0x85, 0xe1, 0x7b, 0xf0, 0x1a, 0x15, 0x52, 0x3d, 0x57, 0xaf,
	0x59, 0x9d, 0xdb, 0x3c, 0x3f, 0xaf, 0xc5, 0x6e, 0xc2, 0x00, 0xb1, 0xfa, 0x21, 0x79, 0x3b, 0xec,
	0x7f, 0xe0, 0x99, 0xcb, 0x36, 0xc5, 0xf5, 0xda, 0x6c, 0x08, 0x80, 0xa8, 0x19, 0x46, 0x5e, 0xa7,
	0x66, 0xc9, 0x45, 0x5e, 0xe4, 0x16, 0xed, 0x56, 0x57, 0x6c, 0x46, 0x82, 0xd7, 0xab, 0xb1, 0x5a,
	0xd2, 0x1e, 0xb0, 0x3b, 0xb0, 0x7b, 0x15, 0xab, 0x65, 0xee, 0xb9, 0x6c, 0x04, 0x2e, 0x1a, 0x6d,
	0x07, 0xbc, 0x7e, 0x9d, 0x70, 0x3d, 0x61, 0xbd, 0x41, 0x9d, 0x9e, 0x9d, 0x82, 0xde, 0x90, 0xdd,
	0x82, 0x11, 0x21, 0x9b, 0xaa, 0x7b, 0x23, 0xe6, 0x42, 0x07, 0xc1, 0x17, 0xfc, 0xb5, 0xe7, 0x55,
	0x31, 0xcf, 0xd4, 0xb4, 0xc8, 0x56, 0xa5, 0x50, 0x4a, 0x24, 0xde, 0xb7, 0x4f, 0x9b, 0xbf, 0x38,
	0x37, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x31, 0x8d, 0x40, 0x45, 0x5f, 0x0b, 0x00, 0x00,
}
